const EVENTS = {
  CONNECT: 'connect',
  CONNECTION: 'connection',
  DATA_CHANNEL_IS_OPEN: 'dataChannelIsOpen',
  DISCONNECT: 'disconnect',
  DISCONNECTED: 'disconnected',
  DROP: 'dropped',
  ERROR: 'error',
  RAW_MESSAGE: 'rawMessage',
  RECEIVED_FROM_DATA_CHANNEL: 'receiveFromDataChannel',
  SEND_OVER_DATA_CHANNEL: 'sendOverDataChannel'
}

const ERRORS = {
  BROWSER_NOT_SUPPORTED: 'BROWSER_NOT_SUPPORTED',
  COULD_NOT_PARSE_MESSAGE: 'COULD_NOT_PARSE_MESSAGE',
  DROPPED_FROM_BUFFERING: 'DROPPED_FROM_BUFFERING',
  MAX_MESSAGE_SIZE_EXCEEDED: 'MAX_MESSAGE_SIZE_EXCEEDED'
}

export { EVENTS, ERRORS }
